# Generated by Django 5.2.6 on 2025-11-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='yandex_place_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID места в Яндекс Картах'),
        ),
        migrations.AddField(
            model_name='university',
            name='yandex_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг Яндекс Карт'),
        ),
        migrations.AddField(
            model_name='university',
            name='yandex_reviews_count',
            field=models.IntegerField(default=0, verbose_name='Количество отзывов в Яндекс Картах'),
        ),
    ]
