# Generated by Django 5.2.6 on 2025-11-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_yandex_place_id_university_yandex_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID места в Google'),
        ),
        migrations.AddField(
            model_name='university',
            name='google_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг Google'),
        ),
        migrations.AddField(
            model_name='university',
            name='google_reviews_count',
            field=models.IntegerField(default=0, verbose_name='Количество отзывов в Google'),
        ),
    ]
