# Generated by Django 5.2.6 on 2025-11-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_university_google_place_id_university_google_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='tabiturient_category',
            field=models.CharField(blank=True, max_length=10, verbose_name='Категория рейтинга (A+, A, B, etc.)'),
        ),
        migrations.AddField(
            model_name='university',
            name='tabiturient_rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='Место в рейтинге Табитуриент.ру'),
        ),
        migrations.AddField(
            model_name='university',
            name='tabiturient_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг Табитуриент.ру'),
        ),
    ]
