# Generated by Django 5.2.6 on 2025-11-08 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_add_tabiturient_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрено администратором')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='universities.university', verbose_name='Университет')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_representatives', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Представитель университета',
                'verbose_name_plural': 'Представители университетов',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'university')},
            },
        ),
    ]
